repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.3.0'
    hooks:
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-case-conflict
      - id: check-added-large-files
      - id: debug-statements
      - id: mixed-line-ending
        args: ["--fix=no"]
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
      - id: end-of-file-fixer
  - repo: https://github.com/asottile/pyupgrade
    rev: 'v2.34.0'
    hooks:
      - id: pyupgrade
        args: ["--py36-plus"]
  - repo: https://github.com/psf/black
    rev: '22.3.0'
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        language_version: python3
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.4'
    hooks:
      - id: bandit
        args: ['--ini', '.bandit']
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.961'
    hooks:
      - id: mypy
        args: ["--install-types", "--non-interactive", "--show-error-codes"]
        additional_dependencies:
          - genutility==0.0.83
          - networkx==2.5
          - numpy==1.19.4
          - scipy==1.5.4
